const itemImg = (seed) =>
  `https://api.dicebear.com/8.x/shapes/svg?seed=${seed}&backgroundColor=242424&shapeColor=fe9f3b`

const userImg = (username) =>
  `https://api.dicebear.com/8.x/pixel-art/svg?seed=${username}&backgroundColor=1d1d1d`

export const listings = [
  {
    id: 1021,
    name: 'Frost Dragon',
    meta: 'Legendary · Neon',
    game: 'Adopt Me',
    category: 'Pet',
    seller: 'user123',
    price: '$10.00',
    views: 142,
    listed: '2h ago',
    status: 'pending',
    image: itemImg('frostdragon'),
  },
  {
    id: 1020,
    name: 'Shadow Dragon',
    meta: 'Legendary · Mega',
    game: 'Adopt Me',
    category: 'Pet',
    seller: 'sellerB',
    price: '$34.00',
    views: 389,
    listed: '3h ago',
    status: 'pending',
    image: itemImg('shadowdragon'),
  },
  {
    id: 1019,
    name: 'Godly Knife',
    meta: 'Rare · Chroma',
    game: 'MM2',
    category: 'Weapon',
    seller: 'knifeking',
    price: '$8.50',
    views: 204,
    listed: '5h ago',
    status: 'approved',
    image: itemImg('godlyknife'),
  },
  {
    id: 1018,
    name: 'Unicorn',
    meta: 'Ultra-Rare · Fly Ride',
    game: 'Adopt Me',
    category: 'Pet',
    seller: 'tradepro',
    price: '$12.00',
    views: 77,
    listed: '6h ago',
    status: 'rejected',
    image: itemImg('unicorn'),
  },
  {
    id: 1017,
    name: 'Ocean Egg',
    meta: 'Limited · Hatched',
    game: 'Adopt Me',
    category: 'Egg',
    seller: 'eggmaster',
    price: '$5.00',
    views: 53,
    listed: '8h ago',
    status: 'pending',
    image: itemImg('oceanegg'),
  },
  {
    id: 1016,
    name: 'Buddha Fruit',
    meta: 'Permanent · Gamepass',
    game: 'Blox Fruits',
    category: 'Fruit',
    seller: 'fruitdealer',
    price: '$6.00',
    views: 120,
    listed: '10h ago',
    status: 'approved',
    image: itemImg('buddhafruit'),
  },
  {
    id: 1015,
    name: 'Dragon Fruit',
    meta: 'Permanent · Perm',
    game: 'Blox Fruits',
    category: 'Fruit',
    seller: 'rpgstore',
    price: '$9.00',
    views: 88,
    listed: '12h ago',
    status: 'pending',
    image: itemImg('dragonfruit'),
  },
  {
    id: 1014,
    name: 'Pet Sim Egg',
    meta: 'Exclusive',
    game: 'Pet Sim X',
    category: 'Egg',
    seller: 'petseller',
    price: '$3.00',
    views: 44,
    listed: '2d ago',
    status: 'approved',
    image: itemImg('petsimegg'),
  },
]

export const orders = [
  {
    id: '#1023',
    item: 'Shadow Dragon',
    itemMeta: 'Legendary',
    buyer: 'userA',
    seller: 'sellerB',
    game: 'Adopt Me',
    amount: '$34.00',
    placed: '2 min ago',
    status: 'delivery',
    itemImage: itemImg('shadowdragon'),
  },
  {
    id: '#1022',
    item: 'Frost Dragon',
    itemMeta: 'Legendary',
    buyer: 'buyer99',
    seller: 'user123',
    game: 'Adopt Me',
    amount: '$10.00',
    placed: '14 min ago',
    status: 'pending',
    itemImage: itemImg('frostdragon'),
  },
  {
    id: '#1021',
    item: 'Godly Knife',
    itemMeta: 'Chroma',
    buyer: 'john_x',
    seller: 'knifeking',
    game: 'MM2',
    amount: '$8.50',
    placed: '1h ago',
    status: 'complete',
    itemImage: itemImg('godlyknife'),
  },
  {
    id: '#1020',
    item: 'Ocean Egg x2',
    itemMeta: 'Limited',
    buyer: 'robloxfan',
    seller: 'eggmaster',
    game: 'Adopt Me',
    amount: '$10.00',
    placed: '1h ago',
    status: 'delivery',
    itemImage: itemImg('oceanegg'),
  },
  {
    id: '#1019',
    item: 'Buddha Fruit',
    itemMeta: 'Permanent',
    buyer: 'gamer22',
    seller: 'fruitdealer',
    game: 'Blox Fruits',
    amount: '$6.00',
    placed: '2h ago',
    status: 'pending',
    itemImage: itemImg('buddhafruit'),
  },
  {
    id: '#1018',
    item: 'Godly Knife',
    itemMeta: 'Chroma',
    buyer: 'john_x',
    seller: 'knifeking',
    game: 'MM2',
    amount: '$8.50',
    placed: '3h ago',
    status: 'dispute',
    itemImage: itemImg('godlyknife'),
  },
]

export const users = [
  {
    username: 'sellerB',
    role: 'Seller',
    email: 'sellerb@mail.com',
    listings: 12,
    orders: 34,
    sales: '$342',
    joined: 'Jan 2025',
    status: 'active',
    image: userImg('sellerB'),
  },
  {
    username: 'tradepro',
    role: 'Seller',
    email: 'tradepro@mail.com',
    listings: 9,
    orders: 21,
    sales: '$215',
    joined: 'Feb 2025',
    status: 'active',
    image: userImg('tradepro'),
  },
  {
    username: 'user123',
    role: 'Seller',
    email: 'user123@mail.com',
    listings: 7,
    orders: 18,
    sales: '$183',
    joined: 'Mar 2025',
    status: 'active',
    image: userImg('user123'),
  },
  {
    username: 'badactor99',
    role: 'Buyer',
    email: 'bad@mail.com',
    listings: 0,
    orders: 3,
    sales: '$0',
    joined: 'Mar 2025',
    status: 'banned',
    image: userImg('badactor99'),
  },
  {
    username: 'robloxfan',
    role: 'Buyer',
    email: 'rfan@mail.com',
    listings: 0,
    orders: 7,
    sales: '$0',
    joined: 'Feb 2025',
    status: 'active',
    image: userImg('robloxfan'),
  },
  {
    username: 'knifeking',
    role: 'Seller',
    email: 'knifeking@mail.com',
    listings: 5,
    orders: 14,
    sales: '$127',
    joined: 'Jan 2025',
    status: 'active',
    image: userImg('knifeking'),
  },
  {
    username: 'eggmaster',
    role: 'Seller',
    email: 'eggmaster@mail.com',
    listings: 4,
    orders: 11,
    sales: '$98',
    joined: 'Feb 2025',
    status: 'active',
    image: userImg('eggmaster'),
  },
]

export const transactions = [
  {
    txnId: 'TXN-8821',
    type: 'Payment',
    typeClass: 'p-approved',
    from: 'userA',
    to: 'sellerB',
    item: 'Shadow Dragon',
    amount: '$34.00',
    amountClass: 'price-val',
    fee: '$3.40',
    net: '$30.60',
    netClass: '',
    date: 'Mar 11, 2:04am',
    status: 'complete',
  },
  {
    txnId: 'TXN-8820',
    type: 'Payment',
    typeClass: 'p-approved',
    from: 'buyer99',
    to: 'user123',
    item: 'Frost Dragon',
    amount: '$10.00',
    amountClass: 'price-val',
    fee: '$1.00',
    net: '$9.00',
    netClass: '',
    date: 'Mar 11, 1:50am',
    status: 'pending',
  },
  {
    txnId: 'TXN-8818',
    type: 'Refund',
    typeClass: 'p-rejected',
    from: 'Platform',
    to: 'gamer22',
    item: 'Unicorn — Dispute #98',
    amount: '-$12.00',
    amountClass: 'neg-val',
    fee: '$0.00',
    net: '-$12.00',
    netClass: 'neg-val',
    date: 'Mar 11, 12:20am',
    status: 'complete',
  },
  {
    txnId: 'TXN-8815',
    type: 'Payment',
    typeClass: 'p-approved',
    from: 'robloxfan',
    to: 'eggmaster',
    item: 'Ocean Egg x2',
    amount: '$10.00',
    amountClass: 'price-val',
    fee: '$1.00',
    net: '$9.00',
    netClass: '',
    date: 'Mar 10, 10:15pm',
    status: 'complete',
  },
  {
    txnId: 'TXN-8810',
    type: 'Payout',
    typeClass: 'p-delivery',
    from: 'Platform',
    to: 'knifeking',
    item: 'Weekly payout',
    amount: '$76.50',
    amountClass: 'blue-val',
    fee: '$0.00',
    net: '$76.50',
    netClass: 'blue-val',
    date: 'Mar 10, 6:00pm',
    status: 'complete',
  },
  {
    txnId: 'TXN-8808',
    type: 'Payment',
    typeClass: 'p-approved',
    from: 'john_x',
    to: 'knifeking',
    item: 'Godly Knife',
    amount: '$8.50',
    amountClass: 'price-val',
    fee: '$0.85',
    net: '$7.65',
    netClass: '',
    date: 'Mar 10, 4:30pm',
    status: 'complete',
  },
]

export const topSellers = [
  { username: 'sellerB', listings: 12, rating: '98%', sales: '$342', image: userImg('sellerB') },
  { username: 'tradepro', listings: 9, rating: '95%', sales: '$215', image: userImg('tradepro') },
  { username: 'user123', listings: 7, rating: '100%', sales: '$183', image: userImg('user123') },
]
